# Generated by Django 4.2.30 on 2026-08-25 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estructura_escolar', '0003_horario_horario_unico_horario_por_dia_asignacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreceptorTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preceptor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preceptor_turno', to=settings.AUTH_USER_MODEL, verbose_name='Preceptor')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preceptores', to='estructura_escolar.turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Preceptor - Turno',
                'verbose_name_plural': 'Preceptores - Turnos',
            },
        ),
    ]
