# Generated by Django 4.2.30 on 2026-08-25 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alumnos', '0001_initial'),
        ('seguimiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('respondida', 'Respondida'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('respuesta', models.TextField(blank=True, verbose_name='Respuesta')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_info', to='alumnos.alumno', verbose_name='Alumno')),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_respondidas', to=settings.AUTH_USER_MODEL, verbose_name='Respondido por')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud de Información',
                'verbose_name_plural': 'Solicitudes de Información',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='Intervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrevista', 'Entrevista'), ('contacto_familia', 'Contacto con familia/tutor'), ('seguimiento', 'Seguimiento pedagógico'), ('derivacion', 'Derivación institucional'), ('acompanamiento', 'Acompañamiento'), ('actividad_especial', 'Propuesta de actividad especial'), ('oportunidad', 'Acceso a proyecto/beca/oportunidad'), ('cierre', 'Cierre de seguimiento'), ('otra', 'Otra')], max_length=30, verbose_name='Tipo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intervenciones', to='alumnos.alumno', verbose_name='Alumno')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intervenciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Intervención',
                'verbose_name_plural': 'Intervenciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
