# Generated by Django 4.2.30 on 2026-08-25 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ciclos_lectivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('manana', 'Mañana'), ('tarde', 'Tarde')], max_length=20, unique=True, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField(help_text='Año de cursado (1 a 6)', verbose_name='Año')),
                ('division', models.CharField(help_text='Letra de la división (A, B, C, D)', max_length=1, verbose_name='División')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('ciclo_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='ciclos_lectivos.ciclolectivo', verbose_name='Ciclo Lectivo')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='estructura_escolar.turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['ciclo_lectivo', 'anio', 'division'],
            },
        ),
        migrations.AddConstraint(
            model_name='curso',
            constraint=models.UniqueConstraint(fields=('anio', 'division', 'turno', 'ciclo_lectivo'), name='unico_curso_por_turno_ciclo'),
        ),
    ]
