# Generated by Django 4.2.30 on 2026-08-25 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estructura_escolar', '0002_materia_asignaciondocente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes')], max_length=10, verbose_name='Día de la semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('asignacion_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='estructura_escolar.asignaciondocente', verbose_name='Asignación Docente')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['asignacion_docente', 'dia_semana', 'hora_inicio'],
            },
        ),
        migrations.AddConstraint(
            model_name='horario',
            constraint=models.UniqueConstraint(fields=('asignacion_docente', 'dia_semana', 'hora_inicio'), name='unico_horario_por_dia_asignacion'),
        ),
    ]
