# Generated by Django 4.2.30 on 2026-08-25 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
        ('estructura_escolar', '0003_horario_horario_unico_horario_por_dia_asignacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ciclos_lectivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoObservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Definición y criterio de uso para reducir interpretaciones', verbose_name='Descripción')),
                ('familia', models.CharField(choices=[('participacion', 'Participación'), ('trabajo_academico', 'Trabajo académico'), ('atencion', 'Atención'), ('convivencia', 'Convivencia'), ('estado_observable', 'Estado observable'), ('evolucion_positiva', 'Evolución positiva'), ('otra', 'Otra situación')], max_length=30, verbose_name='Familia')),
                ('caracter', models.CharField(choices=[('positivo', 'Positivo'), ('neutro', 'Neutro'), ('atencion', 'Atención')], default='neutro', max_length=20, verbose_name='Carácter')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versión')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalogo_creado', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Catálogo de Observación',
                'verbose_name_plural': 'Catálogo de Observaciones',
                'ordering': ['familia', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(help_text='Momento del hecho observado', verbose_name='Fecha y hora')),
                ('turno', models.CharField(choices=[('manana', 'Mañana'), ('tarde', 'Tarde')], max_length=20, verbose_name='Turno')),
                ('comentario', models.TextField(blank=True, help_text='Comentario opcional con contexto adicional', verbose_name='Comentario')),
                ('dentro_horario', models.BooleanField(default=False, verbose_name='Dentro del horario de clase')),
                ('anulada', models.BooleanField(default=False, verbose_name='Anulada')),
                ('motivo_anulacion', models.TextField(blank=True, verbose_name='Motivo de anulación')),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de anulación')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observaciones', to='alumnos.alumno', verbose_name='Alumno')),
                ('anulada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones_anuladas', to=settings.AUTH_USER_MODEL, verbose_name='Anulada por')),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observaciones', to='observaciones.catalogoobservacion', verbose_name='Categoría')),
                ('ciclo_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observaciones', to='ciclos_lectivos.ciclolectivo', verbose_name='Ciclo Lectivo')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observaciones', to='estructura_escolar.curso', verbose_name='Curso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observaciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Docente')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observaciones', to='estructura_escolar.materia', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Observación',
                'verbose_name_plural': 'Observaciones',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.AddConstraint(
            model_name='catalogoobservacion',
            constraint=models.UniqueConstraint(fields=('nombre', 'version'), name='unico_nombre_version_catalogo'),
        ),
    ]
