# Generated by Django 4.2.30 on 2026-08-26 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estructura_escolar', '0003_horario_horario_unico_horario_por_dia_asignacion'),
        ('observaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observacion',
            name='materia',
            field=models.ForeignKey(blank=True, help_text='Opcional para observaciones de preceptoría', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observaciones', to='estructura_escolar.materia', verbose_name='Materia'),
        ),
    ]
