# Generated by Django 4.2.30 on 2026-08-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('docente', 'Docente'), ('preceptor', 'Preceptor'), ('directivo', 'Directivo'), ('admin', 'Admin')], default='docente', help_text='Rol institucional del usuario', max_length=20, verbose_name='Rol'),
        ),
    ]
