# Generated by Django 4.2.30 on 2026-08-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CicloLectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(help_text='Año del ciclo lectivo (ej: 2026)', verbose_name='Año')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('estado', models.CharField(choices=[('planificado', 'Planificado'), ('activo', 'Activo'), ('cerrado', 'Cerrado')], default='planificado', max_length=20, verbose_name='Estado')),
                ('activo', models.BooleanField(default=True, help_text='Indica si este ciclo está disponible para uso')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ciclo Lectivo',
                'verbose_name_plural': 'Ciclos Lectivos',
                'ordering': ['-anio'],
            },
        ),
        migrations.AddConstraint(
            model_name='ciclolectivo',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('anio',), name='unico_ciclo_activo_por_anio'),
        ),
    ]
