# Generated by Django 4.2.30 on 2026-08-25 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ciclos_lectivos', '0001_initial'),
        ('estructura_escolar', '0003_horario_horario_unico_horario_por_dia_asignacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.CharField(blank=True, max_length=20, verbose_name='DNI')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('egresado', 'Egresado'), ('trasladado', 'Trasladado')], default='activo', max_length=20, verbose_name='Estado')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionAlumnoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('condicion', models.CharField(choices=[('regular', 'Regular'), ('repitente', 'Repitente'), ('movilidad', 'Movilidad')], default='regular', max_length=20, verbose_name='Condición')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_curso', to='alumnos.alumno', verbose_name='Alumno')),
                ('ciclo_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_alumnos', to='ciclos_lectivos.ciclolectivo', verbose_name='Ciclo Lectivo')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alumnos_asignados', to='estructura_escolar.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Asignación Alumno-Curso',
                'verbose_name_plural': 'Asignaciones Alumno-Curso',
                'ordering': ['ciclo_lectivo', 'curso', 'alumno'],
            },
        ),
        migrations.AddConstraint(
            model_name='asignacionalumnocurso',
            constraint=models.UniqueConstraint(fields=('alumno', 'curso', 'ciclo_lectivo'), name='unica_asignacion_alumno_curso_ciclo'),
        ),
    ]
