# Generated by Django 4.2.30 on 2026-08-25 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('modificar', 'Modificar'), ('eliminar', 'Eliminar'), ('anular', 'Anular'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('solicitar', 'Solicitar'), ('responder', 'Responder')], max_length=20, verbose_name='Acción')),
                ('modelo', models.CharField(help_text='Nombre del modelo afectado', max_length=100, verbose_name='Modelo')),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID del objeto')),
                ('detalles', models.JSONField(blank=True, default=dict, help_text='Datos adicionales en formato JSON', verbose_name='Detalles')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-timestamp'],
            },
        ),
    ]
