# Generated by Django 4.2.30 on 2026-08-25 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
        ('estructura_escolar', '0003_horario_horario_unico_horario_por_dia_asignacion'),
        ('ciclos_lectivos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('tardanza', 'Tardanza'), ('justificado', 'Justificado')], default='presente', max_length=20, verbose_name='Estado')),
                ('hora_llegada', models.TimeField(blank=True, help_text='Solo para tardanzas', null=True, verbose_name='Hora de llegada')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='alumnos.alumno', verbose_name='Alumno')),
                ('ciclo_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='ciclos_lectivos.ciclolectivo', verbose_name='Ciclo Lectivo')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='estructura_escolar.curso', verbose_name='Curso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Docente')),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='estructura_escolar.materia', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Registro de Asistencia',
                'verbose_name_plural': 'Registros de Asistencia',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddConstraint(
            model_name='registroasistencia',
            constraint=models.UniqueConstraint(fields=('alumno', 'fecha', 'materia', 'curso'), name='unico_registro_asistencia'),
        ),
    ]
